# Generated by Django 3.0.4 on 2020-03-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='services',
            field=models.ManyToManyField(blank=True, to='api.UserService'),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_hours',
            field=models.ManyToManyField(blank=True, to='api.WorkingHour'),
        ),
    ]
