# Generated by Django 3.0.4 on 2020-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='work_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='work_until',
            field=models.TimeField(),
        ),
    ]
