# Generated by Django 3.0.4 on 2020-05-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='benefit_discount',
            field=models.FloatField(default=0.1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='benefit_requirement',
            field=models.IntegerField(default=5, null=True),
        ),
    ]
