# Generated by Django 3.0.4 on 2020-05-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200510_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Rating'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[('pending', 0), ('active', 1), ('finished', 2), ('cancelled', 3)], default=0),
        ),
    ]
