# Generated by Django 3.0.4 on 2020-05-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200514_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullrequest',
            name='edits',
            field=models.ManyToManyField(to='api.RequestEdit'),
        ),
        migrations.AddField(
            model_name='report',
            name='handled',
            field=models.BooleanField(default=False),
        ),
    ]
