# Generated by Django 3.0.4 on 2020-06-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fcmdevice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FCMDevice',
        ),
    ]
