# Generated by Django 3.0.4 on 2020-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200507_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghour',
            name='work_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='work_until',
            field=models.DateTimeField(),
        ),
    ]
