# Generated by Django 3.0.5 on 2020-06-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[('request', 0), ('offer', 1), ('edit_request', 2), ('rating', 3), ('achievement', 4), ('test', 5)]),
        ),
    ]
