# Generated by Django 3.0.4 on 2020-03-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200318_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBlocked',
        ),
    ]
