# Generated by Django 3.0.4 on 2020-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200611_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='body_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_sr',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_sr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[('req_direct', 0), ('req_failed', 1), ('offer_created', 2), ('offer_accepted', 3), ('offer_canceled', 4), ('edit_created', 5), ('edit_accepted', 6), ('edit_canceled', 7), ('rating', 8), ('achievement', 9), ('req_success', 10)]),
        ),
    ]
