# Generated by Django 3.0.4 on 2020-06-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200618_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='working_with',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='location',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Location'),
        ),
        migrations.AddField(
            model_name='request',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
