# Generated by Django 3.0.4 on 2020-05-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_fulluser_edits'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Request'),
        ),
    ]
