# Generated by Django 3.0.4 on 2020-03-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200319_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tasklist',
            field=models.ManyToManyField(to='api.Task'),
        ),
    ]
