# Generated by Django 3.0.5 on 2020-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_request_tasklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[('pending', 0), ('active', 1)], default=0),
        ),
    ]
