# Generated by Django 3.0.4 on 2020-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_report_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pictures',
            field=models.ManyToManyField(to='api.Picture'),
        ),
    ]
