# Generated by Django 3.0.4 on 2020-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_report_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
