# Generated by Django 3.0.4 on 2020-05-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='handled',
        ),
    ]
