# Generated by Django 3.0.4 on 2020-05-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_report_handled'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='finished_created_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='finished_working_with',
            field=models.BooleanField(default=False),
        ),
    ]
